---
version: '3.8'
services:
  cockroach.db:
    container_name: node_1
    image: cockroachdb/cockroach:latest
    volumes:
      - db:/cockroach/cockroach-data
    command: start-single-node --insecure
    ports:
      - '26257:26257'
      - '8080:8080'

volumes:
  db:
