---
version: '3.8'
services:
  postgres.db:
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - pg-db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DATABASE: todos

volumes:
  pg-db:
